version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - DB_HOST=host.docker.internal
      - PORT=${PORT}  # Use the PORT variable from .env
    depends_on:
      - redis
    ports:
      - "3003:${PORT}"  

  redis:
    image: redis:latest
    ports:
      - "6379:6379" 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
      timeout: 5s
