name: CI pipeline

on:
  push:
    paths:
      - 'week4Assignment/**'
    branches:
      - main

jobs:
  deploy-to-ec2:
    runs-on: self-hosted  # This is your EC2 runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy app to server
        run: |
          
          # If Node.js project
          npm install
          pm2 restart app || pm2 start server.js --name app
