name: Build and Push to Ec2

# Trigger the workflow when code is pushed to the main branch
on:
  push:
    paths:
      - 'week4Assignment/**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Docker Buildx for advanced building
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to DockerHub using credentials
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./week4Assignment
          file: ./week4Assignment/Dockerfile
          push: true
          tags: bishal1030/express-application:latest
          
      # Step 5: Run docker-compose on EC2
      - name: Run docker-compose
        run: |
          cd /home/ubuntu/app
          docker compose pull express_app
          docker compose up -d

